export enum UiIcon {
  at = 'at',
  check = 'check',
  clipboard = 'clipboard',
  dollar = 'dollar',
  euro = 'euro',
  github = 'github',
  key = 'key',
  menu = 'menu',
  minusCircle = 'minusCircle',
  moon = 'moon',
  pencil = 'pencil',
  plusCircle = 'plusCircle',
  spinner = 'spinner',
  sun = 'sun',
  table = 'table',
  trash = 'trash',
  dismiss = 'dismiss',
  exclamation = 'exclamation',
  x_circle = 'x_circle',
  check_circle = 'check_circle',
  information_circle = 'information_circle',
  user = 'user',
  thumb_up = 'thumb_up',
}
