export enum UiIcon {
  at = 'at',
  check = 'check',
  dollar = 'dollar',
  euro = 'euro',
  github = 'github',
  key = 'key',
  menu = 'menu',
  minusCircle = 'minusCircle',
  moon = 'moon',
  pencil = 'pencil',
  plusCircle = 'plusCircle',
  spinner = 'spinner',
  sun = 'sun',
  table = 'table',
  trash = 'trash',
}
